[package]
name = "boids"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.88"

[dependencies.web-sys]
version = "0.3.65"
features = [
    "CanvasRenderingContext2d",
]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
